package com.wkwan.cmput301assignment1;

import java.io.Serializable;
import java.util.ArrayList;

// This class is designed to store any and all of the claims that
// users create with the application. Users can then access, review,
// add, remove, etc. the stored claims.

public class ClaimStore implements Serializable {

	// Serialization code that is automatically generated by Eclipse
	private static final long serialVersionUID = -8771693475540777136L;
    
	private ArrayList<ClaimCreate> claims = null;
	
	public ClaimStore() {
		claims = new ArrayList<ClaimCreate>();
	}
	
	public ArrayList<ClaimCreate> getClaims() {
		return claims;
	}
	
	public void addClaim(ClaimCreate claim) {
		claims.add(claim);
	}
	
	public void removeClaim(ClaimCreate claim) {
		claims.remove(claim);
	}
	
	public ClaimCreate getClaim(int index) {
		return claims.get(index);
	}
	
	public boolean contains(ClaimCreate claim) {
		return claims.contains(claim);
	}
	
	public int amount() {
		return claims.size();
	}

	public int orderOf(Object object) {
	    return claims.indexOf(object);
    }
}